language: go
go: 1.5

before_install:
  - mkdir -p $HOME/gopath/src/github.com/gtalent/liccor
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/gtalent/liccor/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/gtalent/liccor
  - cd $HOME/gopath/src/github.com/gtalent/liccor

install:
  - go get

script:
  - make
